name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Login to Environment
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://org240f3a48.crm4.dynamics.com'
        user-name: ${{ secrets.USERID }}
        password-secret: ${{ secrets.PASSWORD }}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://org240f3a48.crm4.dynamics.com'
        user-name: ${{ secrets.USERID }}
        password-secret: ${{ secrets.PASSWORD }}
        solution-name: ALMTest
        solution-output-file: out/exported/ALMLab.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/ALMLab.zip
        solution-folder: out/solutions/ALMLab
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/ALMLab
        solution-target-folder: solutions/ALMLab
        repo-token: ${{ secrets.TOKEN }}
        allow-empty-commit: true
